"""
Local Git client for writing generated files into a repository and creating a
real commit without requiring the GitHub API.
"""

import asyncio
import json
from pathlib import Path
from typing import Dict

from core.models import GeneratedCode, TestResult, UserStory
from utils.logger import get_logger

logger = get_logger(__name__)


class LocalGitClient:
    """Apply generated files into a local Git repository and create a commit."""

    def __init__(self, repo_path: str):
        self.repo_path = Path(repo_path).resolve()

    async def commit_code(
        self,
        user_story: UserStory,
        generated_code: GeneratedCode,
        test_result: TestResult,
    ) -> str:
        await self._assert_git_repo()
        files = self._collect_files(generated_code, test_result)
        self._write_files(files)
        await self._git("add", "--", *sorted(files.keys()))

        diff_exit = await self._git(
            "diff",
            "--cached",
            "--quiet",
            check=False,
        )
        if diff_exit == 0:
            head_sha = (await self._git("rev-parse", "HEAD", capture_output=True)).strip()
            logger.info("  No staged changes detected; reusing current HEAD")
            return head_sha

        await self._git(
            "-c",
            "user.name=AI-SDLC-Pipeline",
            "-c",
            "user.email=ai-sdlc@noreply.local",
            "commit",
            "-m",
            self._build_commit_message(user_story, test_result),
        )
        head_sha = (await self._git("rev-parse", "HEAD", capture_output=True)).strip()
        logger.info(f"  ✓ Local Git commit: {head_sha[:8]}")
        return head_sha

    async def _assert_git_repo(self) -> None:
        await self._git("rev-parse", "--is-inside-work-tree", capture_output=True)

    def _write_files(self, files: Dict[str, str]) -> None:
        for relative_path, content in files.items():
            full_path = self.repo_path / relative_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")

    async def _git(
        self,
        *args: str,
        capture_output: bool = False,
        check: bool = True,
    ) -> str | int:
        proc = await asyncio.create_subprocess_exec(
            "git",
            *args,
            cwd=str(self.repo_path),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        stdout_text = stdout.decode("utf-8", errors="replace")
        stderr_text = stderr.decode("utf-8", errors="replace")
        if check and proc.returncode != 0:
            raise RuntimeError(
                f"Git command failed in {self.repo_path}: git {' '.join(args)}\n{stderr_text.strip()}"
            )
        if capture_output:
            return stdout_text
        return proc.returncode

    def _collect_files(
        self,
        generated_code: GeneratedCode,
        test_result: TestResult,
    ) -> Dict[str, str]:
        files: Dict[str, str] = {}
        files.update(generated_code.files)
        files.update(test_result.test_files)

        if generated_code.pom_xml:
            files["pom.xml"] = generated_code.pom_xml
        if generated_code.readme:
            files["README.md"] = generated_code.readme

        files[".ai-sdlc/test-report.json"] = json.dumps(
            test_result.to_dict(),
            indent=2,
            ensure_ascii=False,
        )
        return files

    def _build_commit_message(self, user_story: UserStory, test_result: TestResult) -> str:
        return (
            f"feat({user_story.id}): {user_story.title}\n\n"
            "Generated by AI-SDLC Pipeline\n\n"
            f"- Test coverage: {test_result.coverage}%\n"
            "- Tests: JUnit 5 + Mockito + AssertJ\n\n"
            f"User Story: {user_story.id}"
        )
