"""
TesterAgent — validates and repairs test files generated by DeveloperAgent.

New responsibility (primary flow):
  1. Receive test files from DeveloperAgent.
  2. Normalize paths (src/main/java → src/test/java for *Test.java files).
  3. Drop out-of-scope tests (e.g. repository tests not in contract).
  4. Apply lightweight sanitizers (package, imports, timeouts, DTO assertThrows).
  5. Repair ONLY src/test/java when test_compilation_failure or test_assertion_failure.
  6. Never create smoke tests, CoverageSafetyNetTest, StoryScopeSmokeTest.
  7. Never modify src/main/java.

Legacy flow (coverage retry only, gated by TESTER_LEGACY_GENERATION_ENABLED):
  test(mode="coverage_retry_targeted") — minimal LLM call for low-coverage classes.
"""

import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from agents.base_agent import BaseAgent
from config.settings import HuggingFaceConfig
from core.models import GeneratedCode, AnalysisResult, TestResult, StoryScope
from utils.logger import get_logger

logger = get_logger(__name__)

_REPAIR_SYSTEM_PROMPT = (
    "You are a Java expert who repairs failing JUnit 5 tests. "
    "You ONLY modify src/test/java files. You NEVER touch src/main/java."
)

_COVERAGE_SYSTEM_PROMPT = """
You are generating additional JUnit 5 test files to increase JaCoCo line coverage.
Rules:
- Generate ONLY src/test/java files.
- Use JUnit 5 + Mockito for services, @WebMvcTest for controllers.
- Never create smoke tests (assertThat(true).isTrue()).
- Never invent methods or constructors absent from the source code.
- Only jakarta.*, never javax.*.
FORMAT: ```java:src/test/java/...Test.java
""".strip()


class TesterAgent(BaseAgent):
    """Validates and repairs test files. Does NOT generate tests freely."""

    def __init__(self, config: HuggingFaceConfig):
        super().__init__(config, "Tester", model=config.model_tester)
        self.min_coverage = float(os.getenv("MIN_TEST_COVERAGE", "80.0"))
        self.use_llm = os.getenv("TESTER_USE_LLM", "true").lower() in ("1", "true", "yes", "on")
        self.safe_test_mode = os.getenv("TESTER_SAFE_MODE", "true").lower() in ("1", "true", "yes", "on")
        # Legacy free-generation disabled by default. DeveloperAgent now owns test generation.
        self._legacy_generation_enabled = os.getenv(
            "TESTER_LEGACY_GENERATION_ENABLED", "false"
        ).lower() in ("1", "true", "yes", "on")
        self._current_generation_diagnostics: list = []
        self._current_weak_test_files: list = []
        logger.info("   Tester → modèle: %s", self.model)
        if self._legacy_generation_enabled:
            logger.warning("   Tester → legacy free generation ENABLED (TESTER_LEGACY_GENERATION_ENABLED=true)")

    # ── Primary entry point ───────────────────────────────────────────────────

    async def validate_and_repair_tests(
        self,
        test_files: Dict[str, str],
        test_contract_dicts: list,
        generated_code: GeneratedCode,
        analysis: AnalysisResult,
        errors: Optional[str] = None,
        error_type: Optional[str] = None,
    ) -> Dict[str, str]:
        """
        Validate and optionally repair developer-generated test files.

        Does NOT generate tests freely. Rules:
        - All paths normalized to src/test/java/.
        - Repository tests dropped unless the contract requests them.
        - Lightweight sanitizers applied (package, imports, timeouts, DTO assertThrows).
        - LLM repair only when errors are provided and error_type is a test failure.
        - src/main/java is NEVER touched.
        """
        logger.info("  [TesterAgent] Validating Developer-generated tests")
        logger.info("  [TesterAgent] Generating tests freely is disabled; using Developer-generated tests")

        from core.test_contract import TestContract
        contract = TestContract.from_dict({
            "story_id": analysis.service_name,
            "test_cases": test_contract_dicts or [],
        })

        if not test_files:
            logger.warning("  [TesterAgent] No test files to validate — returning empty set")
            return {}

        # Step 1: Normalize paths and enforce src/test/java prefix
        validated = self._normalize_test_paths(test_files)

        # Step 2: Drop repository tests not in contract
        if not contract.has_repository_tests():
            filtered: Dict[str, str] = {}
            for path, content in validated.items():
                if "Repository" in Path(path).name and "Test" in Path(path).name:
                    logger.info(
                        "  [TesterAgent] Repository test skipped — not in test contract: %s", path
                    )
                    continue
                filtered[path] = content
            validated = filtered

        # Step 3: Sanitize each file
        sanitized: Dict[str, str] = {}
        for path, content in validated.items():
            result = self._sanitize_test_file(path, content, generated_code, analysis)
            if result is not None:
                sanitized[path] = result

        # Step 4: Repair if errors provided
        if errors and error_type in ("test_compilation_failure", "test_assertion_failure"):
            logger.info(
                "  [TesterAgent] %s detected — repairing tests only",
                error_type.replace("_", " ").title(),
            )
            repaired = await self._repair_test_files_only(
                sanitized, generated_code, analysis, errors, error_type, contract
            )
            for path, content in repaired.items():
                norm = path.replace("\\", "/")
                if norm.startswith("src/test/java/"):
                    sanitized[norm] = content

        logger.info("  [TesterAgent] Validation complete — %d test file(s) accepted", len(sanitized))
        return sanitized

    # ── Path normalization ────────────────────────────────────────────────────

    # Files that load the full Spring Boot context and slow down isolated story tests.
    _SLOW_CONTEXT_TEST_PATTERNS = ("ApplicationTests.java",)

    def _normalize_test_paths(self, test_files: Dict[str, str]) -> Dict[str, str]:
        """Normalize test paths. Moves *Test.java from src/main → src/test automatically.

        ApplicationTests.java is excluded by default because it loads the entire
        Spring Boot context and routinely causes Maven test timeouts on CI.
        Set TESTER_INCLUDE_APPLICATION_TESTS=true to override this behaviour.
        """
        include_app_tests = os.getenv("TESTER_INCLUDE_APPLICATION_TESTS", "false").lower() in (
            "1", "true", "yes", "on"
        )
        result: Dict[str, str] = {}
        for path, content in test_files.items():
            norm = path.replace("\\", "/")
            is_test_file = norm.endswith("Test.java") or norm.endswith("Tests.java")

            # Skip full-context bootstrap tests unless explicitly enabled
            if not include_app_tests and any(
                norm.endswith(p) for p in self._SLOW_CONTEXT_TEST_PATTERNS
            ):
                logger.info(
                    "  [TesterAgent] Excluded slow full-context test: %s "
                    "(set TESTER_INCLUDE_APPLICATION_TESTS=true to keep it)",
                    norm,
                )
                continue

            if is_test_file and norm.startswith("src/main/java/"):
                fixed = "src/test/java/" + norm[len("src/main/java/"):]
                logger.info("  [TesterAgent] Normalized test path from %s to %s", norm, fixed)
                norm = fixed
            elif is_test_file and norm.startswith("main/java/"):
                fixed = "src/test/java/" + norm[len("main/java/"):]
                logger.info("  [TesterAgent] Normalized test path from %s to %s", norm, fixed)
                norm = fixed
            elif is_test_file and norm.startswith("java/"):
                fixed = "src/test/java/" + norm[len("java/"):]
                logger.info("  [TesterAgent] Normalized test path from %s to %s", norm, fixed)
                norm = fixed

            if not norm.startswith("src/test/java/"):
                logger.warning("  [TesterAgent] Ignored test file outside src/test/java: %s", path)
                continue
            result[norm] = content
        return result

    # ── File sanitizer ────────────────────────────────────────────────────────

    def _sanitize_test_file(
        self,
        path: str,
        content: str,
        generated_code: GeneratedCode,
        analysis: AnalysisResult,
    ) -> Optional[str]:
        """Apply lightweight fixes to a single test file. Returns None to reject."""
        if not content.strip():
            return None

        # Fix package declaration to match path
        content = self._fix_package(path, content)

        # Fix common import mistakes
        content = content.replace("import javax.persistence.", "import jakarta.persistence.")
        content = content.replace(
            "org.springframework.boot.test.autoconfigure.orm.jpa.AutoConfigureTestDatabase",
            "org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase",
        )

        # Fix ServiceImpl import — always in .impl subpackage
        import re as _re
        def _fix_service_impl_import(m):
            pkg = m.group(1)
            cls = m.group(2)
            if pkg.endswith(".impl"):
                return m.group(0)  # already correct
            return f"import {pkg}.impl.{cls};"
        content = _re.sub(
            r"import ([\w.]+)\.(\w+ServiceImpl);",
            _fix_service_impl_import,
            content,
        )

        # Remove fragile assertThrows(IllegalArgumentException) on DTOs
        content = self._remove_dto_assert_throws(content, generated_code)

        # Add missing JUnit static imports
        uses_junit_assertions = any(
            tok in content
            for tok in ["assertThrows(", "assertDoesNotThrow(", "assertAll(", "assertEquals("]
        )
        if uses_junit_assertions and "import static org.junit.jupiter.api.Assertions" not in content:
            content = re.sub(
                r"(package\s+[\w\.]+;\n)",
                r"\1\nimport static org.junit.jupiter.api.Assertions.*;\n",
                content, count=1,
            )

        # Fix wrong-arity constructors for DTOs — replace new Foo(args) with new Foo()
        content = self._fix_dto_constructors(content, generated_code)

        # Fix Response/Request/DTO constructors with args → use no-arg constructor
        import re as _re2
        content = _re2.sub(
            r"new\s+(\w*(?:Response|Request|DTO|Dto))\s*\([^)]+\)",
            lambda m: f"new {m.group(1)}()",
            content,
        )

        # Add @Timeout on @Test methods
        content = self._add_timeouts(content)

        # Deduplicate imports
        lines = content.splitlines()
        seen: set = set()
        deduped: list = []
        for line in lines:
            if line.startswith("import "):
                if line in seen:
                    continue
                seen.add(line)
            deduped.append(line)
        content = "\n".join(deduped)

        # Trim anything after the last closing brace of the class
        last_brace = content.rfind("}")
        if last_brace != -1:
            content = content[:last_brace + 1]

        return content

    # ── Sanitizer helpers ─────────────────────────────────────────────────────

    def _fix_package(self, path: str, content: str) -> str:
        normalized = path.replace("\\", "/")
        pkg_match = re.search(r"src/(?:test|main)/java/(.+)/[^/]+\.java$", normalized)
        if not pkg_match:
            return content
        expected = pkg_match.group(1).replace("/", ".")
        declared = re.search(r"^\s*package\s+([a-zA-Z0-9_.]+)\s*;", content, re.MULTILINE)
        if declared:
            if declared.group(1) != expected:
                return re.sub(
                    r"^\s*package\s+[a-zA-Z0-9_.]+\s*;\s*",
                    f"package {expected};\n\n",
                    content, count=1, flags=re.MULTILINE,
                )
            return content
        return f"package {expected};\n\n{content.lstrip()}"

    def _remove_dto_assert_throws(self, content: str, generated_code: GeneratedCode) -> str:
        """Remove assertThrows(IllegalArgumentException) on DTO constructors unless production code actually throws."""
        if "assertThrows(IllegalArgumentException.class" not in content:
            return content
        for src in generated_code.files.values():
            if "throw new IllegalArgumentException" in src:
                return content
        cleaned = re.sub(
            r"assertThrows\s*\(\s*IllegalArgumentException\.class\s*,\s*\(\s*\)\s*->[^;]+;\s*\)",
            "/* sanitized: DTO does not throw IllegalArgumentException — use Jakarta Validator */\n"
            "            assertTrue(true)",
            content,
        )
        cleaned = re.sub(
            r"assertThrows\s*\(\s*IllegalArgumentException\.class\s*,\s*\(\s*\)\s*->[^;]+;\s*\)\s*;",
            "/* sanitized: DTO does not throw IllegalArgumentException — use Jakarta Validator */",
            cleaned,
        )
        if cleaned != content:
            logger.warning("  [TesterAgent] Removed fragile assertThrows(IllegalArgumentException) on DTO")
        return cleaned

    def _fix_dto_constructors(self, content: str, generated_code) -> str:
        """Replace new DtoClass(args...) with DtoClass.builder()...build() when arg count mismatches."""
        import re as _re
        # Find all DTO/Response/Request classes from generated code
        dto_classes = set()
        for path in (generated_code.main_files if hasattr(generated_code, "main_files") else {}).keys():
            name = path.replace("\\", "/").split("/")[-1].replace(".java", "")
            if any(s in name for s in ("Response", "Request", "DTO", "Dto")):
                dto_classes.add(name)

        for cls in dto_classes:
            # Match: new ClassName(arg1, arg2, ...)
            pattern = _re.compile(rf"new\s+{cls}\s*\(([^)]+)\)")
            for match in pattern.finditer(content):
                args_str = match.group(1).strip()
                # Get actual fields from generated code
                src = None
                for path, src_content in (generated_code.main_files if hasattr(generated_code, "main_files") else {}).items():
                    if path.replace("\\", "/").endswith(f"/{cls}.java"):
                        src = src_content
                        break
                if not src:
                    continue
                fields = _re.findall(r"private\s+\w+\s+(\w+)\s*;", src)
                args = [a.strip() for a in args_str.split(",")]
                if len(args) != len(fields):
                    # Build setter-based replacement
                    var_name = cls[0].lower() + cls[1:]
                    replacement_lines = [f"new {cls}()"]
                    for field in fields:
                        setter = "set" + field[0].upper() + field[1:]
                        replacement_lines.append(f"/* {var_name}.{setter}(...); */")
                    # Replace constructor call with new ClassName() and add comment
                    content = content.replace(
                        match.group(0),
                        f"new {cls}()",
                        1,
                    )
        return content

    def _add_timeouts(self, content: str) -> str:
        """Add @Timeout(10) to @Test methods and the required import if missing."""
        if "@Test" not in content and "@ParameterizedTest" not in content:
            return content
        if "import org.junit.jupiter.api.Timeout;" not in content:
            import_block = "import org.junit.jupiter.api.Timeout;\n"
            import_match = list(re.finditer(r"^\s*import\s+[a-zA-Z0-9_.*]+\s*;\s*$", content, re.MULTILINE))
            if import_match:
                last = import_match[-1]
                content = content[:last.end()] + "\n" + import_block + content[last.end():]
            else:
                pkg_match = re.search(r"^\s*package\s+[a-zA-Z0-9_.]+\s*;\s*", content, re.MULTILINE)
                if pkg_match:
                    content = content[:pkg_match.end()] + "\n" + import_block + content[pkg_match.end():]
        content = re.sub(
            r"(@(?:Test|ParameterizedTest)(?:\s*\n\s*@[^ \n][^\n]*)*)\n(\s*void\s+)",
            lambda m: m.group(1) + ("\n    @Timeout(10)" if "@Timeout(" not in m.group(1) else "") + "\n" + m.group(2),
            content,
        )
        return content

    # ── LLM repair ────────────────────────────────────────────────────────────

    async def _repair_test_files_only(
        self,
        test_files: Dict[str, str],
        generated_code: GeneratedCode,
        analysis: AnalysisResult,
        errors: str,
        error_type: str,
        contract: Any,
    ) -> Dict[str, str]:
        """Ask LLM to repair failing tests. Production code is NEVER editable."""
        if not self.use_llm:
            logger.info("  [TesterAgent] LLM disabled — skipping test repair")
            return test_files

        contract_snippet = getattr(contract, "to_prompt_snippet", lambda: "")()
        test_context = "\n\n".join(
            f"// === {p} ===\n{c[:1500]}"
            for p, c in list(test_files.items())[:5]
        )
        production_summary = "\n".join(
            f"// {p}: {c.splitlines()[0] if c.strip() else '(empty)'}"
            for p, c in list(generated_code.files.items())[:6]
            if p.replace("\\", "/").startswith("src/main/java/")
        )

        msg = f"""Repair the failing test files below. You may ONLY modify src/test/java files.

ERROR TYPE: {error_type}
{errors[:2000]}

TEST CONTRACT:
{contract_snippet}

CURRENT TEST FILES:
{test_context}

PRODUCTION CODE (read-only — DO NOT MODIFY):
{production_summary}

Rules:
- Never modify src/main/java.
- Never invent methods or fields absent from the source code.
- For validation: use Validation.buildDefaultValidatorFactory() + validator.validate().
- NEVER: assertThrows(IllegalArgumentException.class, () -> new Dto(...))

FORMAT: ```java:src/test/java/path/ClassNameTest.java""".strip()

        try:
            response = await self.call_llm(
                system_prompt=_REPAIR_SYSTEM_PROMPT,
                user_message=msg,
                max_tokens=4096,
            )
            repaired_raw = self.extract_code_blocks(response)
            repaired: Dict[str, str] = {}
            for path, content in repaired_raw.items():
                norm = path.replace("\\", "/")
                if norm.startswith("src/test/java/") and content.strip():
                    repaired[norm] = content
                else:
                    logger.warning(
                        "  [TesterAgent] Ignored production file change during test repair: %s", path
                    )
            logger.info("  [TesterAgent] Test-only repair applied — %d file(s) updated", len(repaired))
            return repaired
        except Exception as exc:
            logger.warning("  [TesterAgent] Test repair LLM call failed: %s", exc)
            return test_files

    # ── Legacy: coverage retry ────────────────────────────────────────────────
    # Gated behind TESTER_LEGACY_GENERATION_ENABLED=false by default.
    # Called only by the pipeline coverage retry loop (mode="coverage_retry_targeted").

    async def test(
        self,
        generated_code: GeneratedCode,
        analysis: AnalysisResult,
        story_scope: Optional[StoryScope] = None,
        mode: str = "initial_full",
        target_classes: Optional[List[str]] = None,
        retry_reason: Optional[str] = None,
        retry_attempt: int = 0,
        existing_test_files: Optional[Dict[str, str]] = None,
    ) -> TestResult:
        """Legacy entry point — only allowed for coverage_retry_targeted."""
        if mode != "coverage_retry_targeted":
            logger.warning(
                "  [TesterAgent] Legacy test() called (mode=%s) — "
                "free generation disabled. Use validate_and_repair_tests().",
                mode,
            )
            return TestResult(
                coverage=0.0,
                passed=False,
                test_files=existing_test_files or {},
                test_summary=f"Legacy free generation disabled (mode={mode})",
                generation_mode=mode,
            )

        if not self.use_llm:
            return TestResult(
                coverage=0.0,
                passed=False,
                test_files=existing_test_files or {},
                test_summary="Coverage retry skipped — LLM disabled",
                generation_mode=mode,
            )

        return await self._coverage_retry(
            generated_code=generated_code,
            analysis=analysis,
            target_classes=target_classes or [],
            existing_tests=existing_test_files or {},
            retry_reason=retry_reason,
            retry_attempt=retry_attempt,
        )

    async def _coverage_retry(
        self,
        generated_code: GeneratedCode,
        analysis: AnalysisResult,
        target_classes: List[str],
        existing_tests: Dict[str, str],
        retry_reason: Optional[str],
        retry_attempt: int,
    ) -> TestResult:
        """Minimal LLM call to add tests for low-coverage classes."""
        if not target_classes:
            return TestResult(
                coverage=0.0,
                passed=False,
                test_files=existing_tests,
                test_summary="Coverage retry: no target classes",
                generation_mode="coverage_retry_targeted",
            )

        logger.info(
            "  [TesterAgent] Coverage retry attempt %d for: %s",
            retry_attempt, ", ".join(target_classes[:5]),
        )

        # Build focused source context
        target_sources = {
            p: c
            for p, c in generated_code.files.items()
            if any(t in p for t in target_classes)
            and p.replace("\\", "/").startswith("src/main/java/")
        }
        source_ctx = "\n\n".join(
            f"// {p}\n{c[:2000]}" for p, c in list(target_sources.items())[:5]
        )
        existing_ctx = "\n".join(
            f"// existing: {p}" for p in list(existing_tests.keys())[:10]
        )

        msg = f"""Add JUnit 5 tests to increase JaCoCo line coverage for these classes:
{", ".join(target_classes)}

Package: {analysis.package_base}

SOURCE CODE:
{source_ctx[:6000]}

EXISTING TESTS (do not duplicate):
{existing_ctx}

Rules:
- src/test/java paths only.
- Mockito for services, @WebMvcTest for controllers.
- No smoke tests, no CoverageSafetyNetTest.
- Only use methods/fields actually present in the source above.

FORMAT: ```java:src/test/java/...Test.java""".strip()

        try:
            response = await self.call_llm(
                system_prompt=_COVERAGE_SYSTEM_PROMPT,
                user_message=msg,
                max_tokens=4096,
                use_cache=False,
                cache_namespace="coverage_retry",
            )
            new_files = self.extract_code_blocks(response)
            merged = dict(existing_tests)
            added = 0
            for path, content in new_files.items():
                norm = path.replace("\\", "/")
                if norm.startswith("src/test/java/") and content.strip():
                    merged[norm] = content
                    added += 1
            logger.info("  [TesterAgent] Coverage retry: %d new test file(s) added", added)
            return TestResult(
                coverage=0.0,
                passed=False,
                test_files=merged,
                test_summary=f"Coverage retry attempt {retry_attempt}: {added} file(s) added",
                generation_mode="coverage_retry_targeted",
                metadata={
                    "target_classes": target_classes,
                    "retry_reason": retry_reason,
                    "retry_attempt": retry_attempt,
                    "weak_test_files": [],
                    "diagnostics": [],
                },
            )
        except Exception as exc:
            logger.warning("  [TesterAgent] Coverage retry LLM call failed: %s", exc)
            return TestResult(
                coverage=0.0,
                passed=False,
                test_files=existing_tests,
                test_summary=f"Coverage retry failed: {exc}",
                generation_mode="coverage_retry_targeted",
            )

    # ── Symbol index (used by sanitizers in other parts of the codebase) ──────

    def _build_project_symbol_index(self, generated_code: GeneratedCode) -> Dict:
        """Build a minimal symbol index from production source files."""
        classes: Dict[str, str] = {}
        methods: Dict[str, set] = {}
        field_specs: Dict[str, list] = {}
        constructor_arities: Dict[str, set] = {}

        for path, content in generated_code.all_source_files().items():
            pkg_m = re.search(r"^\s*package\s+([a-zA-Z0-9_.]+)\s*;", content, re.MULTILINE)
            type_m = re.search(r"\b(?:class|interface|enum)\s+([A-Z][A-Za-z0-9_]*)\b", content)
            if not pkg_m or not type_m:
                continue
            name = type_m.group(1)
            fqcn = f"{pkg_m.group(1)}.{name}"
            classes[name] = fqcn

            methods[name] = {
                m.group(1)
                for m in re.finditer(
                    r"\b(?:public|protected|private)\s+[\w<>\.,\[\]\s]+\s+([a-zA-Z_][A-Za-z0-9_]*)\s*\(",
                    content,
                )
                if m.group(1) != name
            }

            specs = [
                (m.group(2), " ".join(m.group(1).split()))
                for m in re.finditer(
                    r"^\s*(?:private|protected|public)\s+(?!static\b)(?:final\s+)?"
                    r"([A-Z][A-Za-z0-9_<>,.\[\]? ]*)\s+([a-zA-Z_][A-Za-z0-9_]*)\s*;\s*$",
                    content, re.MULTILINE,
                )
            ]
            if specs:
                field_specs[name] = specs

            arities: set = {
                len([p for p in params.split(",") if p.strip()])
                for params in re.findall(
                    rf"\b{re.escape(name)}\s*\(([^)]*)\)\s*\{{", content, re.MULTILINE
                )
            } or {0}
            if "@AllArgsConstructor" in content and specs:
                arities.add(len(specs))
            if "@NoArgsConstructor" in content:
                arities.add(0)
            if "@RequiredArgsConstructor" in content:
                required = [
                    n for n, _ in specs
                    if re.search(
                        rf"^\s*(?:private|protected|public)\s+final\s+[A-Z][\w<>,.\[\]? ]+\s+{re.escape(n)}\s*;\s*$",
                        content, re.MULTILINE,
                    )
                ]
                arities.add(len(required))
            constructor_arities[name] = arities

        return {
            "classes": classes,
            "methods": methods,
            "field_specs": field_specs,
            "constructor_arities": constructor_arities,
        }

    # ── Stubs kept for backward compatibility with imports elsewhere ──────────
    # These are no-ops so nothing breaks if they are called.

    def _sanitize_generated_tests(
        self,
        test_files: Dict[str, str],
        generated_code: GeneratedCode,
        analysis: AnalysisResult,
    ) -> Dict[str, str]:
        """Compatibility stub — use validate_and_repair_tests() instead."""
        result: Dict[str, str] = {}
        for path, content in test_files.items():
            sanitized = self._sanitize_test_file(path, content, generated_code, analysis)
            if sanitized is not None:
                result[path] = sanitized
        return result

    def _normalize_test_file_path(self, path: str) -> str:
        """Compatibility stub — use _normalize_test_paths() instead."""
        norm = (path or "").strip().replace("\\", "/")
        if norm.startswith("src/test/"):
            return norm
        if norm.startswith("src/main/java/"):
            return "src/test/java/" + norm[len("src/main/java/"):]
        if norm.startswith("main/java/"):
            return "src/test/java/" + norm[len("main/java/"):]
        return f"src/test/java/{norm.lstrip('/')}"

    def _ensure_test_timeouts(self, content: str) -> str:
        """Compatibility alias."""
        return self._add_timeouts(content)

    def _sanitize_dto_assert_throws(self, content: str, generated_code: GeneratedCode) -> str:
        """Compatibility alias."""
        return self._remove_dto_assert_throws(content, generated_code)

    def _ensure_package_matches_path(self, path: str, content: str) -> str:
        """Compatibility alias."""
        return self._fix_package(path, content)
